apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false # do not push to hub.docker.com
  artifacts:
  - image: andreyohiienko/multi-client
    context: client # ref to folder
  docker:
    dockerfile: Dockerfile.dev
  sync:
    '**/*.js': .
    '**/*.css': .
    '**/*.html': .
deploy:
  kubectl:
    manifests:
    # do not add databaseses
    - k8s/client-deployment.yaml
    - k8s/server-deployment.yaml
    - k8s/worker-deployment.yaml
    - k8s/server-cluser-ip-service.yaml
    - k8s/client-cluser-ip-service.yaml