apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false # do not push to hub.docker.com
  artifacts:
  - image: andreyohiienko/multi-client
    context: client # ref to folder
  docker:
    dockerfile: Dockerfile.dev
  sync:
    '**/*.js': .
    '**/*.css': .
    '**/*.html': .