apiVersion: v1
kind: Service
metadata:
  name: client-deployment
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
  - port: 3000 # for other Pod
    targetPort: 3000 # inside a container
