apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  acme:
    server: https://acme-v02.api.letsenctypt.org/directory
    email: 'andreyohiieko@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
